apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv01
  labels:
    speed: fastssd
spec:
  accessModes: ["ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  nfs:
    path: /nfs/data/1
    server: k8s01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv02
  labels:
    speed: fastssd
spec:
  accessModes: ["ReadOnlyMany","ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  nfs:
    path: /nfs/data/2
    server: k8s01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv03
  labels:
    speed: fastssd
spec:
  accessModes: ["ReadOnlyMany","ReadWriteMany","ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  nfs:
    path: /nfs/data/3
    server: k8s01


